image: ubuntu:latest

services:
  - name: docker:dind
    alias: docker

variables:
  DOCKER_DIND: "docker:24.0.5-dind"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: "tcp://docker:2375"
  FF_NETWORK_PER_BUILD: "true"
  CI_DEBUG_SERVICES: "true"
  DOCKER_DRIVER: overlay2

stages:
  - auto-fix

auto-fix:
  stage: auto-fix
  tags: [ saas-linux-medium-amd64 ]

  rules:
    - if: $ISSUE_TYPE == "note" || $ISSUE_TYPE == "issue" || ($CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_LABELS =~ /\bfix-me\b/)
      when: always
    - when: never

  cache:
    key: pip-openhands-cache
    paths:
      - .cache/pip

  variables:
    LLM_MODEL: "anthropic/claude-3-5-sonnet-20241022"
    MAX_ITERATIONS: "50"
    TARGET_BRANCH: "master"

  before_script:
    # ----------------------------------------------------------------------------
    # 1) Install Docker + Python + venv, then create and activate a virtual environment
    # ----------------------------------------------------------------------------
    - apt-get update
    - apt-get install -y --no-install-recommends docker.io python3.12 python3.12-venv python3-pip git ca-certificates build-essential python3.12-dev libffi-dev curl
    - python3.12 -m venv /builds/$CI_PROJECT_PATH/venv
    - source /builds/$CI_PROJECT_PATH/venv/bin/activate
    - pip install --upgrade pip
    - python --version
    - pip --version
    - docker version # Check if docker daemon is running before continuing

  script:
    - source /builds/$CI_PROJECT_PATH/venv/bin/activate

    # --------------------------------------------------------
    # 1) Clone & "editable" install + symlink pyproject.toml
    # --------------------------------------------------------
    - |
      echo "=== Step 1: Cloning & Installing OpenHands in editable mode ==="
      git clone "https://oauth2:${GITLAB_API_TOKEN}@gitlab.com/symbaventures/research-and-development/OpenHands.git" /builds/$CI_PROJECT_PATH/OpenHands
      cd /builds/$CI_PROJECT_PATH/OpenHands

      if [ "$IS_EXPERIMENTAL" = "true" ]; then
        echo "Switching to 'resolver_gitlab' branch..."
        git checkout resolver_gitlab_pipeline
      else
        echo "Using 'main' branch..."
        git checkout resolver_gitlab_pipeline
      fi

      echo "Installing OpenHands in editable mode..."
      pip install -e .

      # Symlink pyproject.toml into the site-packages directory so code that
      # tries to read it there won't crash with FileNotFoundError
      PYPROJECT_LOCAL="/builds/$CI_PROJECT_PATH/OpenHands/pyproject.toml"
      PYPROJECT_SITE="$(python -c 'import site; print(site.getsitepackages()[0])')/pyproject.toml"

      if [ -f "$PYPROJECT_LOCAL" ]; then
        echo "Symlinking $PYPROJECT_LOCAL => $PYPROJECT_SITE"
        ln -sf "$PYPROJECT_LOCAL" "$PYPROJECT_SITE"
      else
        echo "Warning: pyproject.toml not found in /builds/$CI_PROJECT_PATH/OpenHands?"
      fi


    # ----------------------------------------------------------------------------
    # 2) Check required environment variables
    # ----------------------------------------------------------------------------
    - |
      echo "=== Step 2: Checking required environment variables ==="
      if [ -z "$LLM_API_KEY" ]; then
        echo "Error: LLM_API_KEY is not set."
        exit 1
      fi
      if [ -z "$GITLAB_API_TOKEN" ]; then
        echo "Error: GITLAB_API_TOKEN is not set. Needed for GitLab API calls and/or pulling OpenHands repo."
        exit 1
      fi
      if [ -z "$GIT_TOKEN" ]; then
        echo "Error: GIT_TOKEN is not set."
        exit 1
      fi
      if [ -z "$GIT_USERNAME" ]; then
        echo "Error: GIT_USERNAME is not set."
        exit 1
      fi
      # Optional warnings:
      if [ -z "$LLM_BASE_URL" ]; then
        echo "Warning: LLM_BASE_URL is not set; default endpoint will be used."
      fi

    # ----------------------------------------------------------------------------
    # 3) (Optional) Comment on the GitLab Issue or MR to note that the pipeline started
    # ----------------------------------------------------------------------------
    - |
      echo "=== Step 3: (Optional) Comment on GitLab to note pipeline start ==="
      if [ "$ISSUE_TYPE" = "issue" ] && [ -n "$ISSUE_IID" ]; then
        NOTE_BODY="Kevin started fixing this issue! You can monitor the progress in GitLab pipeline #$CI_PIPELINE_ID."
        curl --request POST \
             --header "PRIVATE-TOKEN: $GIT_TOKEN" \
             --form "body=${NOTE_BODY}" \
             "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/issues/$ISSUE_IID/notes"
        echo ""
      elif [ "$CI_PIPELINE_SOURCE" = "merge_request_event" ] && [ -n "$CI_MERGE_REQUEST_IID" ]; then
        NOTE_BODY="Kevin started fixing this Merge Request! You can monitor the progress in GitLab pipeline #$CI_PIPELINE_ID."
        curl --request POST \
             --header "PRIVATE-TOKEN: $GIT_TOKEN" \
             --form "body=${NOTE_BODY}" \
             "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/$CI_MERGE_REQUEST_IID/notes"
        echo ""
      else
        echo "Skipping note creation — missing \$ISSUE_TYPE or \$ISSUE_IID / \$CI_MERGE_REQUEST_IID."
      fi

    # ----------------------------------------------------------------------------
    # 4) Attempt to resolve the issue with OpenHands
    # ----------------------------------------------------------------------------
    - |
      echo "=== Step 4: Attempt to resolve issue with OpenHands ==="
      cd /builds/$CI_PROJECT_PATH
      export DEBUG=1
      export LOG_ALL_EVENTS=true
      export SANDBOX_LOCAL_RUNTIME_URL=http://docker
      export LLM_MODEL="anthropic/claude-3-5-sonnet-20241022"
      export LLM_API_KEY="${LLM_API_KEY}"
      export GIT_TOKEN="${GIT_TOKEN}"
      export GIT_USERNAME="${GIT_USERNAME}"
      export GITLAB_TOKEN="${GITLAB_API_TOKEN}"
      python -m openhands.resolver.resolve_issue \
        --repo "$CI_PROJECT_PATH" \
        --issue-number "${ISSUE_IID:-0}" \
        --issue-type "${ISSUE_TYPE:-issue}" \
        --max-iterations "$MAX_ITERATIONS" \
        --username "${GIT_USERNAME}" \
        --token "${GIT_TOKEN}" \
        --llm-model "anthropic/claude-3-5-sonnet-20241022" \
        --llm-api-key "${LLM_API_KEY}" \
        --comment-id "${COMMENT_ID:-None}" \
        --output-dir "/builds/$CI_PROJECT_PATH/output" \
        --is-experimental "${IS_EXPERIMENTAL:-false}" \
        --runtime-container-image "docker.all-hands.dev/all-hands-ai/runtime:0.20-nikolaik" \
        || true
      # Note: '|| true' ensures we don't automatically fail here; 
      # we'll check success/failure next.

    # ----------------------------------------------------------------------------
    # 5) Check resolution result
    # ----------------------------------------------------------------------------
    - |
      echo "=== Step 5: Checking resolution result ==="
      RESOLUTION_SUCCESS="false"
      if grep -q '"success":true' /builds/$CI_PROJECT_PATH/output/output.jsonl; then
        RESOLUTION_SUCCESS="true"
      fi
      echo "Resolution success? => $RESOLUTION_SUCCESS"
      echo "RESOLUTION_SUCCESS=$RESOLUTION_SUCCESS" >> $CI_JOB_VARIABLES_FILE

    # ----------------------------------------------------------------------------
    # 6) Create "draft MR" or push a branch depending on success
    # ----------------------------------------------------------------------------
    - |
      echo "=== Step 6: Create draft MR or push branch ==="
      cd /builds/$CI_PROJECT_PATH
      if [ "$RESOLUTION_SUCCESS" = "true" ]; then
        python -m openhands.resolver.send_pull_request \
          --issue-number ${ISSUE_IID:-0} \
          --pr-type draft \
          --token "$GITLAB_API_TOKEN" \
          --username Kevin \
          --pr-title "Potential fix for ${ISSUE_TYPE:-issue} ${ISSUE_IID:-0} from Kevin" | tee pr_result.txt && \
          grep "merge_requests/[0-9]*" pr_result.txt | sed 's/.*\///g' > pr_number.txt
      else
        python -m openhands.resolver.send_pull_request \
          --issue-number "${ISSUE_IID:-0}" \
          --pr-type branch \
          --send-on-failure | tee branch_result.txt && \
          grep "compare/main...[^ ]*" branch_result.txt | sed 's/.*\.\.\.//g' > branch_name.txt
      fi

    
    # ----------------------------------------------------------------------------
    # 7) Analyze logs and handle success/failure comments
    # ----------------------------------------------------------------------------
    - |
      echo "=== Step 7: Analyze push logs and create response comments ==="
      cd /builds/$CI_PROJECT_PATH
      AGENT_RESPONDED="false"

      # Read result files
      PR_NUMBER=""
      BRANCH_NAME=""
      RESULT_EXPLANATION=""

      if [ "$RESOLUTION_SUCCESS" = "true" ] && [ -f "pr_number.txt" ]; then
        PR_NUMBER=$(cat pr_number.txt)
      elif [ -f "branch_name.txt" ]; then
        BRANCH_NAME=$(cat branch_name.txt)
      fi

      # Get result explanation from output.jsonl for failed resolution
      if [ "$RESOLUTION_SUCCESS" != "true" ] && [ -f "output/output.jsonl" ]; then
        RESULT_EXPLANATION=$(head -n 1 output/output.jsonl | python3 -c "import sys, json; print(json.loads(sys.stdin.read()).get('result_explanation', ''))" || echo "")
      fi

      # Handle successful resolution with PR
      if [ "$RESOLUTION_SUCCESS" = "true" ] && [ -n "$PR_NUMBER" ]; then
        if [ "$ISSUE_TYPE" = "issue" ] && [ -n "$ISSUE_IID" ]; then
          NOTE_BODY="A potential fix has been generated and a draft MR #${PR_NUMBER} has been created. Please review the changes."
          curl --request POST \
              --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" \
              --form "body=$NOTE_BODY" \
              "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/issues/$ISSUE_IID/notes"
          AGENT_RESPONDED="true"
        elif [ "$ISSUE_TYPE" = "pr" ] && [ -n "$MR_IID" ]; then
          NOTE_BODY="A potential fix has been generated and a draft MR #${PR_NUMBER} has been created. Please review the changes."
          curl --request POST \
              --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" \
              --form "body=$NOTE_BODY" \
              "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/$MR_IID/notes"
          AGENT_RESPONDED="true"
        fi

      # Handle unsuccessful resolution with branch creation
      elif [ "$RESOLUTION_SUCCESS" != "true" ] && [ -n "$BRANCH_NAME" ]; then
        NOTE_BODY="An attempt was made to automatically fix this issue, but it was unsuccessful. A branch named '${BRANCH_NAME}' has been created with the attempted changes. You can view the branch at $CI_PROJECT_URL/-/tree/${BRANCH_NAME}. Manual intervention may be required."
        
        if [ -n "$RESULT_EXPLANATION" ]; then
          NOTE_BODY="$NOTE_BODY\n\nAdditional details about the failure:\n$RESULT_EXPLANATION"
        fi

        if [ "$ISSUE_TYPE" = "issue" ] && [ -n "$ISSUE_IID" ]; then
          curl --request POST \
              --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" \
              --form "body=$NOTE_BODY" \
              "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/issues/$ISSUE_IID/notes"
          AGENT_RESPONDED="true"
        elif [ "$ISSUE_TYPE" = "mr" ] && [ -n "$MR_IID" ]; then
          curl --request POST \
              --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" \
              --form "body=$NOTE_BODY" \
              "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/$MR_IID/notes"
          AGENT_RESPONDED="true"
        fi
      fi

    # ----------------------------------------------------------------------------
    # 8) Fallback error comment if no response was made
    # ----------------------------------------------------------------------------
    - |
      echo "=== Step 8: Post fallback error comment if needed ==="
      if [ "$AGENT_RESPONDED" != "true" ]; then
        ERROR_NOTE="The workflow to fix this issue encountered an error. Please check the pipeline logs for more information: $CI_PROJECT_URL/-/pipelines/$CI_PIPELINE_ID"
        
        if [ "$ISSUE_TYPE" = "issue" ] && [ -n "$ISSUE_IID" ]; then
          curl --request POST \
              --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" \
              --form "body=$ERROR_NOTE" \
              "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/issues/$ISSUE_IID/notes"
        elif [ "$ISSUE_TYPE" = "mr" ] && [ -n "$MR_IID" ]; then
          curl --request POST \
              --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" \
              --form "body=$ERROR_NOTE" \
              "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/merge_requests/$MR_IID/notes"
        fi
      fi
  artifacts:
    name: "resolver-output"
    when: always
    paths:
      - /builds/$CI_PROJECT_PATH/output/output.jsonl
    expire_in: 30 days
